### ISSUE TITLE
[7/6][Code Review] No Need for Semicolons at the end of Swift lines

### ISSUE THREAD

**Issue by metamattrosemeier** [Abdulla2022/Vegetarian-Food-Finder-#10]
https://github.com/Abdulla2022/Vegetarian-Food-Finder-/blob/66b99fc4c799f14952b17c78cbdcf4f2aa9632c7/Vegetarian-Food-Finder/Controller/LoginViewController.swift#L23

You can delete the semicolon 👍

**Comment by Abdulla2022** [comment]
Done
