### ISSUE TITLE
[7/11][Code Review] Remove Duplicated Code That Already Exists in `StoryboardIdentifiable`

### ISSUE THREAD

**Issue by metamattrosemeier** [Abdulla2022/Vegetarian-Food-Finder-#17]
https://github.com/Abdulla2022/Vegetarian-Food-Finder-/blob/05ec563f529a6e8c0027e8fc69634555a7af8dc1/Vegetarian-Food-Finder/Controller/LoginViewController.swift#L31

Hey! Since this view controller already conforms to `StoryboardIdentifiable`, you don't need to instantiate your "Main" storyboard like this here.  You can delete the whole line starting with `let storyboard = ...`

And then update the next line to access the `storyboard` var you get from the `StoryboardIdentifiable` protocol:
```
let tabBarController = Self.storyBoard.instantiateViewController(withIdentifier: "TabBarController") as? UITabBarController
```

(Notice the `Self.` in there with a capital S.  The capital S means you're referring to the type (`LoginViewController`), and could also be done by typing `LoginViewController.` instead.  But the `Self.` is shorter and cleaner)

**Comment by Abdulla2022** [comment]
Done
