### ISSUE TITLE
[7/6][Code Review] - Leverage empty lines for code legibility

### ISSUE THREAD

**Issue by gustavopolitano** [Abdulla2022/Vegetarian-Food-Finder-#5]
This applies to most files.

Make sure you optimize the code for reading. One of the tools to improve legibility is to make more conscious usage of empty lines to create visually distinct areas of code.

This will vary per project (styling guides might differ). But overall it's a good practice to have an empty line:
1. Before each class declaration (including between import blocks and the class)
2. Before each function (including between variable declaration and functions)

**Comment by Abdulla2022** [comment]
Done
