### ISSUE TITLE
[7/6][Code Review] Likely Copy and Paste Error in username string 

### ISSUE THREAD

**Issue by metamattrosemeier** [Abdulla2022/Vegetarian-Food-Finder-#8]
https://github.com/Abdulla2022/Vegetarian-Food-Finder-/blob/66b99fc4c799f14952b17c78cbdcf4f2aa9632c7/Vegetarian-Food-Finder/Controller/LoginViewController.swift#L18

Looks like you wanted this instead:

```
let username = loginUserName.text
```

**Comment by Abdulla2022** [comment]
Done
